
import React from 'react';
import type { ChatMessage as ChatMessageType } from '../types';
import { DownloadIcon, SpinnerIcon } from './Icons';

interface ChatMessageProps {
  message: ChatMessageType;
}

export const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const handleDownload = (imageUrl: string, filename: string = 'ai-image.png') => {
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (message.sender === 'user') {
    return (
      <div className="flex justify-end my-2">
        <div className="bg-blue-600 text-white rounded-lg p-3 max-w-lg">
          {message.image && (
            <img src={message.image.url} alt={message.image.name} className="rounded-md mb-2 max-h-48" />
          )}
          <p className="text-base">{message.text}</p>
        </div>
      </div>
    );
  }

  // AI Message
  return (
    <div className="flex justify-start my-2">
      <div className="bg-gray-700 text-white rounded-lg p-3 max-w-lg">
        {message.isLoading && (
          <div className="flex items-center justify-center h-64 w-64">
            <SpinnerIcon className="w-10 h-10" />
          </div>
        )}
        {message.error && (
          <div className="text-red-400">
            <p><strong>Error:</strong> {message.error}</p>
          </div>
        )}
        {message.imageUrl && (
          <div className="relative group">
            <img src={message.imageUrl} alt="Generated by AI" className="rounded-md max-w-full h-auto" />
            <button
              onClick={() => handleDownload(message.imageUrl!)}
              className="absolute top-2 right-2 bg-black bg-opacity-50 text-white p-2 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
              aria-label="Download image"
            >
              <DownloadIcon className="w-5 h-5" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
};
